<a href="https://colab.research.google.com/github/pravinrb22/ML-and-Data-Analysis-Project/blob/main/TIME_SERIES_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing the libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import acf, pacf
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [2]:
#Loading the dataset
data = pd.read_csv("Complete_Blasting_info.csv")

In [15]:
data.head()

,Unnamed: 0,PM10 (µg/m3),NO (µg/m3),PM2.5 (µg/m3),NO2 (µg/m3),NOX (ppb),CO (mg/m3),SO2 (µg/m3),NH3 (µg/m3),Ozone (µg/m3),Benzene (µg/m3)
DateTime,,,,,,,,,,,
2023-02-01 00:00:00,0,95.0,14.484070,35.0,90.1,56.2,0.31,11.986833,17.7,28.1,0.4
2023-02-01 00:15:00,1,95.0,14.484070,35.0,88.0,55.1,0.33,11.986833,18.3,27.1,0.4
2023-02-01 00:30:00,2,95.0,15.835914,35.0,87.7,55.2,0.38,10.912796,19.7,24.9,0.4
2023-02-01 00:45:00,3,122.0,15.914518,34.0,88.9,55.7,0.38,10.613291,21.3,21.9,0.4
2023-02-01 01:00:00,4,122.0,16.035640,34.0,90.0,55.8,0.38,7.362361,22.3,16.7,0.4

In [ ]:
# Combine 'Date' and 'Time' columns into a single datetime column
data['DateTime'] = pd.to_datetime(data['Date'] + ' ' + data['Time'])

In [ ]:
# Drop the separate 'Date' and 'Time' columns
data.drop(['Date', 'Time'], axis=1, inplace=True)

In [ ]:
# Set 'DateTime' column as the index
data.set_index('DateTime', inplace=True)

In [ ]:
# Set 'DateTime' column as the index
data.set_index('DateTime', inplace=True)